rails_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "top#index"
  resources :microposts,    only: [:new, :create, :destroy]
  get "index" => "top#index"

  namespace :api do
    get "index" => "top#index"
    resources :users, only: [:index, :show]
    resources :microposts,    only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
  end
end

rails_app/app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

rails_app/app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

rails_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :nickname, presence: true, length: { maximum: 20, allow_blank: true }, uniqueness: { case_sensitive: false }
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  default_scope -> { order('created_at DESC') }

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

rails_app/app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  protect_from_forgery with: :null_session
  # respond_to :json
  # before_action :authenticate_user!

  def current_user
    User.find_by(nickname: "taro")
  end
end

rails_app/app/controllers/api/microposts_controller.rb
class Api::MicropostsController < Api::BaseController
  before_action :set_micropost, only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.json { render :show, status: :created, location: @micropost }
      else
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @micropost.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    def set_micropost
      @micropost = current_user.microposts.find(params[:id])
    end

    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

rails_app/app/controllers/api/relationships_controller.rb
class Api::RelationshipsController < Api::BaseController
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    user = User.find(params[:id])
    current_user.unfollow!(user)
    respond_to do |format|
      format.js
    end
  end
end

rails_app/app/controllers/api/top_controller.rb
class Api::TopController < Api::BaseController
  def index
    @microposts = current_user.feed
  end
end

rails_app/app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts
  end
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :nickname
      devise_parameter_sanitizer.for(:account_update) << :nickname
    end
end

rails_app/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:destroy]

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = current_user.microposts.build(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to root_path, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = current_user.microposts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

rails_app/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if current_user
      @microposts = current_user.microposts
    end
  end
end

rails_app/app/helpers/api/base_helper.rb
module Api::BaseHelper
end

rails_app/app/helpers/api/microposts_helper.rb
module Api::MicropostsHelper
end

rails_app/app/helpers/api/relationships_helper.rb
module Api::RelationshipsHelper
end

rails_app/app/helpers/api/top_helper.rb
module Api::TopHelper
end

rails_app/app/helpers/api/users_helper.rb
module Api::UsersHelper
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/helpers/microposts_helper.rb
module MicropostsHelper
  def current_user?(user)
    user == current_user
  end
end

rails_app/app/helpers/top_helper.rb
module TopHelper
end

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.nickname %></strong>.
      <%= link_to 'edit profile', edit_user_registration_path %> |
      <%= link_to "sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "sign up", new_user_registration_path %> |
      <%= link_to "sign in", new_user_session_path %>
    <% end %>
  </nav>
</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

rails_app/app/views/microposts/_micropost.html.erb
<li>
  <span class="nickname"><%= micropost.user.nickname %>
  </span>
  <span class="content"><%= simple_format micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

rails_app/app/views/microposts/new.html.erb
<h1>New Micropost</h1>
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/top/index.html.erb
<% if current_user %>
  <%= link_to "new micropost", new_micropost_path %>

  <%= render @microposts %>
<% end %>